apiVersion: apps/v1
kind: Deployment
metadata:
  name: miweb-deployment
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: miweb
  template:
    metadata:
      labels:
        app: miweb
    spec:
      containers:
      - name: miweb
        image: "${DOCKER_IMAGE}"  
        ports:
        - containerPort: 80  
---
apiVersion: v1
kind: Service
metadata:
  name: miweb-service
spec:
  selector:
    app: miweb
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 80  
  type: LoadBalancer  
