name: CI/CD Pipeline
run-name: "Esta siendo ejecutado por ${{github.actor}}"

on:
  workflow_dispatch:


jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: Clonado repositorio
              uses: actions/checkout@v2

            - name: Configurar Docker Buildx
              uses: docker/setup-buildx-action@v2
              with:
                version: latest
            - name: Construir imagen
              run: |
                docker build -t my-nodejs-app:latest .
            - name: Crear docker imagen
              run: |
                sudo docker run --rm my-nodejs-app:latest npm test
            - name: Run SonarQube Scanner
              uses: SonarSource/sonarcloud-github-action@v2
              env:
                SONAR_TOKEN: 3b826c6cf29ff2d8e882599439413cb862dc6db2    

    cd: 
        runs-on: ubuntu-latest
        needs: ci
        env: 
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        steps:
            - name: Subir la imagen a docker
              run: |
                echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
                sudo docker tag my-nodejs-app:latest myregistry.com/my-nodejs-app:latest
                sudo docker push myregistry.com/my-nodejs-app:latest
            - name: Deploy to Production (Docker Compose)
              run: |
                  ssh -o StrictHostKeyChecking=no user@production-server "
                    cd /path/to/docker-compose-directory &&
                    docker-compose pull &&
                    docker-compose up -d"
              
