name: "Segundo Action"
run-name: "Ejecutado por ${{ github.actor }}"

on: 
    workflow_call:
jobs:

    run-test:
        env:
            username: ${{secrets.USERNAME}}
            password: ${{secrets.PASSWORD}}

        runs-on: ubuntu-latest
        strategy:
            matrix: 
                scripts: ["test1.sh","test2.sh","test3.sh"]
        steps:
            - name: Clonar repositorio
              uses: actions/checkout@v4
            - name: Dar permisos
              run: chmod +x scripts/${{ matrix.scripts}}
            - name: Ejecutar los scripts
              run: ./scripts/${{ matrix.scripts }}
    rollback:
        runs-on: ubuntu-latest
        needs: run-test
        if: ${{failure()}}
        steps:
            - name: Rollback
              run: echo " Error haciendo los tests"
