name: Tercer Action
run-name: Este tercer action esta siendo ejecutado ${{ github.actor }}

on: 
   workflow_dispatch:
    inputs:
        entornos:
            description: "Seleccione un entorno"
            required: true
            default: "dev"
            type: choice
            options: 
                - dev
                - test
                - pro

jobs:
    prueba_tercer_action:
        runs-on: ubuntu-latest
        environment: ${{ github.event.inputs.entornos }}
        env:
            url: ${{ secrets.API_URL}}
            key: ${{ secrets.API_KEY}}

        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Despliegue de entornos
            run: echo "Desplegando en el entorno ${{ github.event.inputs.entornos }}"
          - name: Resultado de datos
            run:  | 
                 run:  | 
                     echo "La url es: ${{ secrets.API_URL }}"
                     echo "La key es: ${{ secrets.API_KEY }}"

